// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4F8xniw_SU0jDq4roYvupfPMpGBpwU9M',
    appId: '1:1097926760848:web:429af81dcac4bcad3f3b15',
    messagingSenderId: '1097926760848',
    projectId: 'camerin-f6671',
    authDomain: 'camerin-f6671.firebaseapp.com',
    storageBucket: 'camerin-f6671.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0NqSA-21Lw3rcWD5Pkp-EVHwdn6CVM24',
    appId: '1:1097926760848:android:f77d75a2bc2289c43f3b15',
    messagingSenderId: '1097926760848',
    projectId: 'camerin-f6671',
    storageBucket: 'camerin-f6671.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHbDPR8myd-Ievb-dlmK4GuJnp5EHqN7c',
    appId: '1:1097926760848:ios:968f9a7878fd8f783f3b15',
    messagingSenderId: '1097926760848',
    projectId: 'camerin-f6671',
    storageBucket: 'camerin-f6671.appspot.com',
    iosBundleId: 'com.example.camerin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHbDPR8myd-Ievb-dlmK4GuJnp5EHqN7c',
    appId: '1:1097926760848:ios:6774bc51ed8669583f3b15',
    messagingSenderId: '1097926760848',
    projectId: 'camerin-f6671',
    storageBucket: 'camerin-f6671.appspot.com',
    iosBundleId: 'com.example.camerin.RunnerTests',
  );
}
